### ISSUE TITLE
Fix broken 404 page

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/core-website#391]
Seems like the 404 page broke in the last theme update.

**Comment by sublibra** [comment]
Seems like the 404 page uses relative URL which doesn't work with 404 which is static. 

There is a fix for this using site_url
https://github.com/mkdocs/mkdocs/pull/1039/commits/f5b5446b71ecfaeaff08da837bd5a0ba7c651fa1
https://www.mkdocs.org/user-guide/configuration/#site_url

However, it doesn't seem to work locally.

**Comment by aihazm** [comment]
@sublibra this code change will actuall fix the sitemap!
=> https://deploy-preview-392--qlikcore.netlify.com/sitemap.xml
vs. https://qlikcore.com/sitemap.xml

in master the URL tags looks like this 
```
<url>
<loc>None</loc>
<lastmod>2018-09-07</lastmod>
<changefreq>daily</changefreq>
</url>
```

**Comment by aihazm** [comment]
The issue has been addressed here => https://github.com/mkdocs/mkdocs/issues/1598 and should have been fixed in mkdocs v1.0.4 (https://github.com/mkdocs/mkdocs/pull/1599)
I am not 100% sure, but switching to mkdocs-material-3.0.4 may fix the issue (it may include latest mkdocs v1.0.4 - see: https://github.com/squidfunk/mkdocs-material/blob/master/requirements.txt#L22)

**Comment by sublibra** [comment]
Good find! I'll test it!

**Comment by peol** [comment]
@JohanBjerning this is solved now, no?

**Comment by sublibra** [comment]
Nope.. Check e.g.
https://core.qlik.com/fdf/dd

**Comment by peol** [comment]
Hm, I know he showed me something locally where this worked a couple of weeks ago :)

**Comment by JohanBjerning** [comment]
There's a branch for upgrading mkdocs-materialui version but contains some issues and haven't had the time to address all of them yet.
