### ISSUE TITLE
Investigate Google Tag Management error 

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/core-website#488]
gtm.js currently throws a type error on the page. There might be a risk that we are not sending the right statistics.

```
VM155:4 Uncaught TypeError: Cannot read property 'get' of undefined
    at k (<anonymous>:4:19)
    at initNewOptimizelyIntegration (<anonymous>:4:120)
    at initOptimizelyIntegration (<anonymous>:4:169)
    at <anonymous>:4:204
    at gtm.js?id=GTM-P7VJSX:3951
    at Object.c [as __html] (gtm.js?id=GTM-P7VJSX:3953)
    at Vb (gtm.js?id=GTM-P7VJSX:3812)
    at g (gtm.js?id=GTM-P7VJSX:3848)
    at gtm.js?id=GTM-P7VJSX:3792
    at Array.<anonymous> (gtm.js?id=GTM-P7VJSX:3850)`
```

**Comment by TRB3269** [comment]
From Abhi — "We just integrated our A/B testing tool (Optimizely). I think this might be related to that. I’ll disable the Optimizely tag to fire on Qlik Dev and Core website because it’s trying to find the Optimizely code which isn’t there on these websites. This won’t affect the stats."

Once this is complete, let's see if this is still an issue.

**Comment by TRB3269** [comment]
Abhi just published the changes which should remedy this. Let us know, thanks.

**Comment by sublibra** [comment]
The page doesn't throw errors anymore so it seems to work.
